name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn
      - name: TypeScript Build
        run: |
          yarn build
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: GitHub Import
        run: |
          RES=`curl -s "https://api.glitch.com/project/githubImport?projectId=${GLITCH_PROJECT_ID}&repo=${REPOSITORY}" -X 'POST' -H "authorization: ${GLITCH_TOKEN}"`
          test "$RES" = "OK"
        env:
          REPOSITORY: ${{ github.repository }}
          GLITCH_PROJECT_ID: ${{ secrets.GLITCH_PROJECT_ID }}
          GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
